export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";

export const PRODUCT_ADMIN_REQUEST = "PRODUCT_ADMIN_REQUEST";
export const PRODUCT_ADMIN_SUCCESS = "PRODUCT_ADMIN_SUCCESS";
export const PRODUCT_ADMIN_FAILS = "PRODUCT_ADMIN_FAILS";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILS";

export const DELETE_PRODUCT_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const DELETE_PRODUCT_FAILS = "PRODUCT_DETAILS_FAILS";


export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAILS = "PRODUCT_CREATE_FAILS";
